config:
  data-home: ${DATA_HOME:/data/gaea/workbench} #数据目录
  shutdown_timeout: ${SHUTDOWN_TIMEOUT:60} #停止服务等待时间，单位秒
  tasks:
    -  #预统计报表
      calssName: com.beagledata.gaea.workbench.scheduled.PreStatReportTask
      cron: ${PRESTATREPORT_CRON:0 0 1 * * ?}
    - #解锁所有资源文件的编辑者
      calssName: com.beagledata.gaea.workbench.scheduled.UnlockAssetsEditorTask
      cron: ${UNLOCKASSETSEDITOR_CROM:0 0 0 * * ?}
  login-retry-number: ${LOGIN_RETRY_NUMBER:10}
  login-retry-time: ${LOGIN_RETRY_TIME:5}
  login-lock-time: ${LOGIN_LOCK_TIME:24}
  pwd-expired-time: ${PWD_EXPIRED_TIME:180}
  dqcurl: ${DQC_URL:http://172.16.150.190:8088/dqc/index.html}
  dqcsession: ${DQC_SESSION:false}

server:
  context-path: ${SERVER_CONTEXT_PATH:/gaea}
  port: ${SERVER_PORT:33005}
  tomcat:
    maxHttpPostSize: -1

spring:
  profiles:
    active: ${ENV:dev}
  datasource:
    druid:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://${DATABASE_IP:127.0.0.1}:3306/${DATABASE_NAME:dqc_gaea}?allowMultiQueries=true&useAffectedRows=true&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8 # mysql主数据库地址
      username: ${DATABASE_USERNAME:cyf} # mysql登录用户
      password: ${DATABASE_PASSWORD:cyf} # mysql登录密码
      connectionProperties: config.decrypt=false
      initialSize: ${DATABASE_INITIAL_SIZE:10}
      minIdle: ${DATABASE_MIN_IDLE:10}
      maxActive: ${DATABASE_MAX_ACTIVE:100}
      maxWait: ${DATABASE_MAX_WAIT:60000}
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: false
      maxPoolPreparedStatementPerConnectionSize: 20
  http:
    multipart:
      maxFileSize: ${UPLOAD_MAX_FILE_SIZE:100Mb}
      maxRequestSize: ${UPLOAD_MAX_REQUEST_SIZE:1000Mb}
      location: ${config.data-home}/tmp
  mvc:
    static-path-pattern: /workbench/**
    favicon:
      enabled: false
  resources:
    static-locations: file:${FRONTEND_PATH:/home/cyf/code/self/dqc/frontend/dist}
  session: #session 存储类型 hash_map 存储本地 redis 存储redis ，存储redid 必须配置redis连接
    store-type: ${SESSION_STORE_TYPE:hash_map}

mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:com/beagledata/gaea/workbench/mapper/*.xml
  type-aliases-package: com.beagledata.gaea.workbench.entity

beagledata:
  security:
    authc:
      private-key: MIIBVQIBADANBgkqhkiG9w0BAQEFAASCAT8wggE7AgEAAkEApOBggPHkxd9mpBXBQPssJd/m0Jcwa3F4l70R/6uuelDjcl01OvTE4iaWSJMV29YZUvKQDBzgUNGuhXmQ/KfjBQIDAQABAkBtmY3tCV9nPbswRhniBVVyk+UOMgKI2bQtQgzt5QUl3v2/zTM2VhUY4wVqagDNrtZJBp1irGfdcmtK0i/UXQLdAiEA6ymZ9JXVPgBl967bVxAnZu7fvywFRGctNccJFCWK/C8CIQCzfGpcq/Sdoo1n79CDNMaejawYn31ahbb3QLs04c2DCwIgUzuaPjN6EkPZ01yUTbBuAcSydNuD0b4jBlG4KOVQ2AkCIQCyd5qW7RB9EZ3DZGyTmg2IqFwf265cLSsB7WZ4LbIYgwIhAMPyzkxBFHhPrPsLN/RpA5Mwj8ELAEYKxG80Rch7Yznw
      captcha:
        enabled: false
    anon:
      - /api/**
      - /rest/**
      - /health

dqc:
  project-uuid: f889d2c558164bfeaaf926deeb7668a7

logging:
  config: ${LOG_CONFIG:classpath:logback-spring.xml}
logback:
  loghome: ${LOG_HOME:logs}
  maxhistory: ${LOG_MAXHISTORY:60}
  maxsize: ${LOG_MAXSIZE:10MB}
  level:
    root: ${LOG_LEVEL:INFO}